// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-KmSnblpM5xioxDoopEu9f6l5eTtyNqE',
    appId: '1:21619564498:web:af475653d2a9fc6207720b',
    messagingSenderId: '21619564498',
    projectId: 'inspiro-quotes-907e0',
    authDomain: 'inspiro-quotes-907e0.firebaseapp.com',
    storageBucket: 'inspiro-quotes-907e0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX7M7pUGYNrXicEDpWdQcueFtFeqA5WDw',
    appId: '1:21619564498:android:5af0f30848dcc7e807720b',
    messagingSenderId: '21619564498',
    projectId: 'inspiro-quotes-907e0',
    storageBucket: 'inspiro-quotes-907e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhHPzOemUjv_yx8mhXT3utM7lOTM_-k1k',
    appId: '1:21619564498:ios:cffdb6bf894fdb4907720b',
    messagingSenderId: '21619564498',
    projectId: 'inspiro-quotes-907e0',
    storageBucket: 'inspiro-quotes-907e0.appspot.com',
    iosBundleId: 'com.example.inspiroQuotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhHPzOemUjv_yx8mhXT3utM7lOTM_-k1k',
    appId: '1:21619564498:ios:81d1d8151811ce2a07720b',
    messagingSenderId: '21619564498',
    projectId: 'inspiro-quotes-907e0',
    storageBucket: 'inspiro-quotes-907e0.appspot.com',
    iosBundleId: 'com.example.inspiroQuotes.RunnerTests',
  );
}
